### PR TITLE
Attribute resolve for colors, dimensions and "raw" attributes

### PR DESCRIPTION
**Pull request by fboldog**
Attribute support required to implement views, layouts like this:

``` xml
    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        app:popupTheme="@style/AppTheme.PopupOverlay" />
```

### CODE REVIEW

**Comment by fboldog** [comment]
conflict fixed :) hoping for merge.

**Comment by yaymalaga** [comment]
Any idea why this commit hasn't been merged? It's really useful

**Comment by Miha-x64** [comment]
Withou this PR, I'm copying attribute-resolving code each time I use Anko DSL.

**Comment by fboldog** [comment]
PR updated to solve actual conflicts.

**Comment by fboldog** [comment]
And `@AttrRes` for all attribute extensions

**Comment by 4u7** [comment]
Thanks for the contribution!

**Comment by fboldog** [comment]
Finally. Thanks! :)

**Pull request merged**
