### PR TITLE
Snackbar View receiver and annotate string resources

### PR DESCRIPTION
**Pull request by hendraanggrian**
Just as there is `Context` receiver in `Toasts.kt`, `Snackbars.kt` should also have `View` receiver.

Also, parameters of string resources should be annotated with `@StringRes`.

### CODE REVIEW

**Comment by hendraanggrian** [comment]
But this version has the same JVM signature with my version. If I combine both versions, it would cause platform declaration clash. I see 2 options here:
 * Abandon old version.
 * Update new version's function names.

What do you think?

**Comment by 4u7** [comment]
Yes, my bad, didn't realise that. I believe that breaking existing codebase to fix minor styling issue is not a good thing. You may try to use `@JvmName` to change signature of new function

**Comment by hendraanggrian** [comment]
Yes that sounds reasonable. I have pushed an update containing previous version as deprecated. New Jvm function names have suffix `2` now.

**Comment by 4u7** [comment]
Could you rebase on current master, please?

**Pull request merged**
