### PR TITLE
fix: #210 add ConstrainLayout support

### PR DESCRIPTION
**Pull request by kuhnroyal**
Usage example:

```kotlin
        constraintLayout {
            guide = guideline {
                id = View.generateViewId()
                layoutParams = ConstraintLayout.LayoutParams(wrapContent, wrapContent).apply {
                    orientation = ConstraintLayout.LayoutParams.VERTICAL
                    guidePercent = 0.5f
                }
            }
            textView {
                backgroundColor = color(R.color.colorAccent)
                text = "Bar"
            }.lparams(wrapContent, wrapContent) {
                bottomToBottom = ConstraintLayout.LayoutParams.PARENT_ID
                topToTop = ConstraintLayout.LayoutParams.PARENT_ID
                leftToLeft = ConstraintLayout.LayoutParams.PARENT_ID
                rightToRight = ConstraintLayout.LayoutParams.PARENT_ID
            }
            textView {
                backgroundColor = color(R.color.colorPrimary)
                text = "Foo"
            }.lparams(wrapContent, wrapContent) {
                bottomToBottom = ConstraintLayout.LayoutParams.PARENT_ID
                leftToLeft = ConstraintLayout.LayoutParams.PARENT_ID
                rightToRight = guide.id
            }
        }
```

### CODE REVIEW

**Comment by JEKos** [comment]
@4u7 can you merge that please?

**Comment by 4u7** [comment]
Thanks for the contribution!
Failed to build, `./gradlew dist` fails with this:
`Exception in thread "main" java.io.FileNotFoundException: dependencies/android-sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.1.0-beta3/constraint-layout-1.1.0-beta3.aar (No such file or directory)`

**Comment by LouisCAD** [comment]
@4u7 Isn't this caused by the fact that ConstraintLayout 1.1.1-beta3 isn't in the SDK anymore, but in the `google()` maven repository? FYI, if you're not using Gradle, it's url is the following: https://dl.google.com/dl/android/maven2/

**Comment by 4u7** [comment]
Merged manually

**Pull request closed without merging**
