### PR TITLE
Add start and end rules to RelativeLayout.LayoutParams extensions.

### PR DESCRIPTION
**Pull request by JimmyRobz**

### CODE REVIEW

**Comment by 4u7** [comment]
Thanks for contribution!
Why not to use constants instead of int literals?
And I think those methods should be annotated with `@RequiresApi(Build.VERSION_CODES.JELLY_BEAN_MR1)`

**Comment by JimmyRobz** [comment]
Thanks for the review.

I did use constants first but I saw that existing functions `alignParentStart` and `alignParentEnd` were using int literals. 

I agree that it would be better with constants and with `@RequestApi` annotation.

I will update the PR with these modifications asap.

**Comment by JimmyRobz** [comment]
@4u7 PR updated with recommandations.

**Comment by 4u7** [comment]
Thank you!

**Pull request merged**
