### PR TITLE
Added textAppearance property

### PR DESCRIPTION
**Pull request by calintat**
I added an extension property for setting the text appearance of a TextView.
It checks the SDK version and calls the appropriate method:
- `setTextAppearance(int resId)` for API level 23+
- `setTextAppearance(Context context, int resId)` otherwise

### CODE REVIEW

**Comment by yanex** [comment]
`setTextAppearance()` looks nice.
By the way, is there need in `horizontalLayout {}`? It already exists and is called `linearLayout {}`.

**Comment by calintat** [comment]
Given there already is a `verticalLayout`, I thought it would make sense to also have a `horizontalLayout` just for completeness.

**Comment by calintat** [comment]
I removed `horizontalLayout`.

**Comment by yanex** [comment]
Merged. Thank you!

**Pull request merged**
