### PR TITLE
Added send sms helper

### PR DESCRIPTION
**Pull request by otomatik**

### CODE REVIEW

**Comment by yanex** [comment]
Maybe add an optional `body` parameter?

```kotlin
intent.putExtra("sms_body", message)
```

**Comment by otomatik** [comment]
@yanex thanks for the suggestion, I just updated the code accordingly ;)

**Comment by carmas123** [comment]
Maybe a good choice rename "sendText" to "sendSMS" to have no conflict with other methods in app.

**Comment by yanex** [comment]
@carmas123 Definitely.

**Comment by otomatik** [comment]
@carmas123 thanks for the suggestion, @yanex done ;)

**Pull request merged**
