### PR TITLE
Added methods for creating and dropping a index.

### PR DESCRIPTION
**Pull request by ZhengKeli**
Indexes are sometimes good for performance, so added two methods. After all, it's just a simple work.

### CODE REVIEW

**Comment by 4u7** [comment]
There is formatting broken in your code, mixed tabs and spaces and missing spaces after : before parameter types. Could you reformat it, please? (there is reformat action in idea)
Otherwise, looks good to me.

**Comment by 4u7** [comment]
Why have you closed it? i would like to merge it

**Comment by ZhengKeli** [comment]
oh I'm new. I'm not very sure what will happen when I

**Comment by 4u7** [comment]
Thank you for contribution!

**Pull request merged**
